### ISSUE TITLE
unexpected grids on map

### ISSUE THREAD

**Issue by jingSUN2017** [aliafzal15/GameProject#24]
Chao, situations which caused the computer dead don't occur in today's testing, but I don't know why red or green grids always unexpectedly shown on the map when playing the game.

I already update and refresh codes multiple times before running the program, could you check it again if the problem I mentioned above exists?

**Comment by chaowangCanada** [comment]
the grid is for my debug purpose. 

You can remove it by uncomment:
        //uiStage.setDebugAll(true);
in  GameScreen.java
